"""empty message

Revision ID: 061fbb0222e8
Revises: 49e2c590bfd2
Create Date: 2023-12-05 19:35:36.007526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061fbb0222e8'
down_revision = '49e2c590bfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
